name: Daily Supply Chain Digest

on:
  schedule:
    - cron: '0 8 * * *'  # Runs every day at 8 AM UTC
  workflow_dispatch:      # Allows manual run

jobs:
  run-digest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install requests python-dotenv

      - name: Run main.py
        env:
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
        run: |
          echo "NEWS_API_KEY=${NEWS_API_KEY}" > .env
          python main.py

      - name: Send digest email
        env:
          GMAIL_ADDRESS: ${{ secrets.GMAIL_ADDRESS }}
          GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
          GMAIL_RECIPIENT: ${{ secrets.GMAIL_RECIPIENT }}
        run: |
          python send_email.py



